### ISSUE TITLE
Contentlist View: banner images in view need to handle mobile breakpoints

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#12]
When the banner images are rendered as previews in the Contentlist view, they are stretched when they hit the landscape smartphone breakpoint. These imagess should either render differently at that breakpoint or be loaded at a sufficient size. Right now they use the 'medium' image style.

**Comment by cornettims** [comment]
When you say stretched, do you just mean that they aren't high enough resolution for the mobile layout? If so, that would be an easy fix, all we'd have to do is change the image style to output a higher resolution image.

**Comment by ashooner** [comment]
Yes, they are being rendered too large for their resolution. It looks like there was a commit to integration that addressed this (and changed the slideshow style). That code is up on the provost dev site now.

**Comment by cornettims** [comment]
Resolved.

**Comment by ashooner** [comment]
Do you know which commit that was in? The latest integration I have still stretches a 220px wide image to full width  at the breakpoint < 640px.

**Comment by cornettims** [comment]
Peter had some changes that affected this -- those were just comitted a few minutes ago. That was probably the missing piece.

**Comment by ashooner** [comment]
I think this is related to switching the contentlist items to `li`s, but now they are at 48% on the smallest breakpoint. Is that intentional?

**Comment by petervcook** [comment]
Does this commit resolve this issue?
