### ISSUE TITLE
Text Only Link in Footer

### ISSUE THREAD

**Issue by jrjenk** [uky-web-archive/seeblue#14]
The Text-Only link still seems to exist in the footer.  The service that provides this on the main UK website (Usablenet.com) will be going under review over the next few months to see if APAT is going to continue to fund this service after June 2014. This aspect may be a point for a larger discussion.

The real question is: if the link is going to be left in, shouldn't it point to the Usablenet service, and provide the URL of the current page so the user is seeing that page as plain text.

**Comment by petervcook** [comment]
You are right, it should be. What is the proper syntax for that URL?

-Peter

**Comment by jrjenk** [comment]
http://assistive.usablenet.com/tt/PAGE_ADDRESS

Where PAGE_ADDRESS is the full path to the page, e.g. http://assistive.usablenet.com/tt/http://www.uky.edu/.  

According to our contact with Usablenet Our licensing only covers pages hosted on the www.uky.edu server, but some impromptu testing shows that it appears to work on several servers as long as they end in .uky.edu

**Comment by cornettims** [comment]
resolved also. There are some open source text lifters out there as well that might work.
