### ISSUE TITLE
Add 'see blue' banner option.

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#15]
This was requested for the Provost site. Or allow banner uploads?

**Comment by petervcook** [comment]
Can you describe in more detail? Do you mean like a banner in the top carousel?

Also, related to see blue.™, in an internal review of the Web Graphic standards today we felt that we should use the see blue.™ branding in more places. We definitely want to add a link to see blue in the top pre-header, and I think that a logo in the footer along side of the University Logo might be a good addition.

**Comment by ashooner** [comment]
By the banner option I mean the image that is loaded into the background of `#header-inner .wrap-inner` via the theme's appearance form. Right now there is a drop-down with two options. The 'see blue' was an option in some earlier mockups, I believe.
