### ISSUE TITLE
Use h1 Element for page headline

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#19]
Currently, content titles are `h2`, and  most pages have no `h1` element

**Comment by petervcook** [comment]
A lot of sites use the site title as the contents for the h1 as we do on the homepage. I would recommend we do that throughout the whole site, not just the homepage as opposed to changing the existing h2-h6 styles.

Related to that, I also noticed the alt tag for the logo should be the site name as specified in site information. We will make that change.

**Comment by ashooner** [comment]
Thanks for the catch on the alt tag. 

I might not have been clear enough about the h1. I just meant that the Drupal node title field should be wrapped in h1 rather than h2. That would be the same content as the html title element, but just without the drupal site name concated to the end.
