### ISSUE TITLE
Appearance: background_logo path domain is sticking in database after migrating and clearing caches

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#22]
After moving the Provost site to www, the 'Header Background' kept dib.uky.edu as the path until the 'SeeBlue Logo' option was reselected and the Appearance form was submitted. We had cleared the cache.

**Comment by cornettims** [comment]
The background_logo path domain is no longer hard coded and uses api functions to determine the appropriate relative path to the images

**Comment by petervcook** [comment]
Andy, does this resolve this issue?
