### ISSUE TITLE
Search results: Remove author and date metadata from output

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#23]
Use the preprocess_search_result hook to omit the user and date from the search output. Ideally this output would be determined by the 'display author and date information', but that is not core behavior.

See: https://drupal.org/comment/5345554#comment-5345554

**Comment by petervcook** [comment]
Would hiding it with CSS be an acceptable solution?

**Comment by ashooner** [comment]
Is the linked solution not working? I’d like to avoid sending unused markup if possible.

**Comment by petervcook** [comment]
We had just played with a CSS solution for the strategic plan site. But I agree, that we should probably completely suppress the output, I doubt any of the sites using the template will want to see the author and modified date.

**Comment by cornettims** [comment]
Author/date information has been surpressed using a template override (see search-result.tpl.php in the theme folder)

**Comment by petervcook** [comment]
I believe this should resolve the issue. Andy, can you confirm?
