### ISSUE TITLE
Smartphone breakpoints: Upper right 'search' icon button does nothing

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#27]
The button in the upper right of the top toolbar (/html/body/div[1]/div/form/fieldset/button) doesn't do anything when tapped at the mobile breakpoints. I'm guessing that it's just a submit button, but the text field is hidden at those breakpoints.

**Comment by cornettims** [comment]
Should be all fixed up in mobile and desktop layouts. All queries are redirected to http://ukcc.uky.edu/cse/
