### ISSUE TITLE
Strict Warning

### ISSUE THREAD

**Issue by jrul222** [uky-web-archive/seeblue#49]
Running into an error every now and then...  I have pulled the current zip from here and installed it and am still getting the error..  also getting it on multiple sites using the theme...  Any idea on this?

![seeblue error](https://cloud.githubusercontent.com/assets/5758688/3162713/2ad4fe6c-eb38-11e3-91f1-c9eb41eeac4b.JPG)

**Comment by jrul222** [comment]
Any word on this?

**Comment by petervcook** [comment]
Who should be assigned to these types of bug fixes? At the moment, Cornett doesn't have an ongoing maintenance plan in place with UKPR for the templates.

**Comment by ashooner** [comment]
Jason, did this error coincide with an upgrade to php 5.4? It looks like that was where this strict warning was implemented.

**Comment by jrul222** [comment]
Hi Andy…  Yes the PHP version was updated…

Regards,

Jason

## 

Jason Ullstam
IS Technical Support Specialist II
Web Content Management
Analytics and Technologies
University of Kentucky
613A CON, 760 Rose Street
Lexington, KY  40536-0232
desk. 859.257.4707
Drupal Information, Support, and Requestshttps://www.uky.edu/cms/
